import time
import os
import pickle
import csv
import glob
from config import argparser
from CAPS.CAPS_main import CAPS_main
from plot_policies import plot_policy_returns
from graphs.plot_graph import plot_apg
from graphs.compare_kernels import compare_explanation_graphs
from graphs.utils import print_kernel_table, select_most_similar_pair, assign_cluster_to_state, get_next_probable_action
from graphs.subgraph_search import get_maximum_common_subgraph, compare_transition_sets, get_transition_differences_at_common_nodes
from graphs.subgraph_search import build_common_percentage_matrices,percentage_table_g1_in_g2, print_percentage_table

from sample_states import test_states_ft, test_states_hw, test_states_dst
from model_paths import paths_ft, paths_hw, paths_dst, paths_hw2
from model_paths import dpmorl_output_dir_ft, dpmorl_output_dir_hw, dpmorl_output_dir_dst, dpmorl_output_dir_hw2
import time

def run_policies(paths, args, experiment_name=None):
    for pol_idx, model_path in enumerate(paths):
        args.path = model_path 
        print(f"\nRunning policy {pol_idx}: {model_path}")
        explanation = CAPS_main(args)
        print(f"Policy {pol_idx} explanation graph generated. {len(explanation['groups'])} nodes and {len(explanation['edges'])} edges.")
        print (f"sample label for policy {pol_idx}: {explanation['groups'][0]}  ")
        all_graphs[f"policy_{pol_idx}"] = explanation
        pkl_file_path = (
            f"outputs/graphs/{args.experiment_name}/"
            f"{args.env}_{args.num_episodes}_{args.lmbda}_{args.compare_criterion}/"
            f"policy_{pol_idx}_graph.pkl"
        )
        with open(pkl_file_path, 'wb') as f:
            pickle.dump(explanation, f)
    return all_graphs

def read_graphs_from_files(paths):
    for pol_idx, model_path in enumerate(paths):
        pkl_file_path = (
            f"outputs/graphs/{args.experiment_name}/"
            f"{args.env}_{args.num_episodes}_{args.lmbda}_{args.compare_criterion}/"
            f"policy_{pol_idx}_graph.pkl"
        )
        if os.path.exists(pkl_file_path):
            with open(pkl_file_path, 'rb') as f:
                explanation = pickle.load(f)
                all_graphs[f"policy_{pol_idx}"] = explanation
                print(f"Loaded graph for policy {pol_idx} from {pkl_file_path}.")
        else:
            print(f"Graph file for policy {pol_idx} not found at {pkl_file_path}. Please run the policies to generate the graphs.")
    return all_graphs
    

if __name__ == '__main__':

    """"
    This is script is for reruning and regenerating the return plots and the explanation
    graphs for the policies generated by DPMORL.
    """

    # Step 1: Collect initial parameters 
    args = argparser()

    test_name= f"{args.env}_{args.num_episodes}_{args.lmbda}_{args.compare_criterion}" 

    if args.env not in ["MO_fruitTree", "MO_highway", "MO_deepSea"]:
        raise ValueError(f"Unknown environment: {args.env}. Please choose from 'MO_fruitTree', 'MO_highway', or 'MO_deepSea'.") 

    env_name = args.env.replace("MO_", "")  # Remove the "MO_" prefix to get the environment name
    if env_name == 'deepSea':
        env_name = 'DeepSeaTreasure'  # Adjust for the specific case of DeepSeaTreasure

    dpmorl_output_dir = f'CAPS/DPMORL/experiments/{args.experiment_name}/DPMORL.{env_name}.LossNormLamda_{args.lmbda}/'

    paths = glob.glob(os.path.join(dpmorl_output_dir, "policy-program-*.zip"))

    paths = [
        path[:-4] if path.endswith(".zip") else path
        for path in paths
    ]
    print(f"Found {len(paths)} policies in {dpmorl_output_dir}.")
    num_pols = len(paths)

    if args.plot_returns == True:
        plots_dir = f"outputs/plots/{args.experiment_name}/{test_name}"
        os.makedirs(plots_dir, exist_ok=True)
        plot_policy_returns(
            env_name=args.env,
            dpmorl_output_dir=dpmorl_output_dir,
            save_dir=plots_dir,
            batch_size=args.batch_size,
            final_episodes=args.final_episodes,
            reward_dims=args.reward_dims
        )

    # Step 2: Run the policy graph computation algorithm for each policy and collect the graphs

    all_graphs = {}

    time_graph_phase = time.time()
    
    if os.path.exists(f"outputs/graphs/{args.experiment_name}/{test_name}"):
        print(f"Directory {test_name} already exists.") 
        if args.use_existing:
            print(f"Using existing graphs from {test_name} as --use_existing flag is set to True. Checking for existing graphs...")
            if len(os.listdir(f"outputs/graphs/{args.experiment_name}/{test_name}")) < len(paths):
                raise ValueError(f"The directory {test_name} is empty or contains "+
                      f"fewer files than expected but the --use_existing flag is  set to True. "+
                      f"Please check if the directory contains the expected graph files.")
            else:
                print(f"""length of files in {test_name}: {len(os.listdir(f"outputs/graphs/{args.experiment_name}/{test_name}"))}, 
                expected: {len(paths)}.
                Re-running the policies to collect new graphs""")
                all_graphs = read_graphs_from_files(paths)
                print(f"Loaded existing graphs from {f'{test_name}'} . {len(all_graphs)} graphs in total.")
        else:
            print(f"Re-running the policies to collect new graphs as --use_existing flag is set to False.")
            all_graphs = run_policies(paths, args)
            print(f"All policies have been tested and graphs collected. {len(all_graphs)} graphs in total.")
    else:
        print(f"Directory {test_name} does not exist. Creating it and running the policies to collect new graphs.")
        os.makedirs(f"outputs/graphs/{args.experiment_name}/{test_name}", exist_ok=True)
        all_graphs = run_policies(paths, args)
        print(f"All policies have been tested and graphs collected. {len(all_graphs)} graphs in total.")

    print(f"All graphs collected:")
    for policy_name, graph in all_graphs.items():
        plot_apg(
            graph,
            title=f"{args.env}_{policy_name}",
            save_path=f"outputs/graphs/{args.experiment_name}/{test_name}"
        )